orkui/controller/controller.Admin.php

Line 1035 is the only code change

Issue #28 - Updated player creation to default to active

---

orkui/template/default/Attendance_park.tpl
orkui/template/default/Player_index.tpl
orkui/template/default/Reports_playerawards.tpl
orkui/template/default/Unit_unitlist.tpl
system/lib/ork3/class.Park.php
system/lib/ork3/class.Player.php
system/lib/ork3/class.Report.php

Corrects issues 154, 165, 166 from
https://github.com/amtgard/ORK3/tree/fix/reports/issue165-incorrect-dues-paid-dates
https://github.com/amtgard/ORK3/tree/fix/units/issue166-missing-unitmundaneid-memory-error
https://github.com/amtgard/ORK3/tree/enhance/reports/issue154-utilize-by-whom-id-in-reports

Sprint 2017 12 19

---

system/lib/ork3/class.Player.php

Adds an optional limit parameter to Player/AttendanceForPlayer

Fixes Issue 209 Add limit to AttendanceForPlayer

---

system/lib/ork3/class.Player.php
system/lib/ork3/class.SearchService.php

Fixes #211 and also added new option for player attendance search for **date_start** so if you were looking for 6 months of attendance you could set date_start and not set limit.

Issue 211 event date_start and add to player attendance

---

system/lib/ork3/class.Player.php

Closes amtgard/ORK3#218
Add module load function, and load Treasury to revoke dues, returning the result

Cannot revoke or add dues via player update

---

system/lib/ork3/class.SearchService.php

Closes #222   Returns the required additional information

Issue 222 SearchService/Player should return suspension information

---

orkui/controller/controller.Kingdom.php

Fixes #227 
This should remove non-active chapters from the Kingdom map.  First time trying an array filter but seems to look/work ok.

Inactive chapters are displayed on Kingdom map

---

orkui/controller/controller.Kingdom.php

Fixes #227
This should remove non-active chapters from the Kingdom map. First time trying an array filter but seems to look/work ok.
Moved to branch local to ORK3 repo @esdraelon.

227 inactive chapter maps

---

system/lib/ork3/class.Award.php

It looks like this fixes #235.  Maybe this worked before and new PHP? I'm not sure. Please can someone else pull and test before merging.

235 misplaced single quote in query

---

system/lib/ork3/class.Report.php

Add MundaneId as parameter to Guilds API

---

.gitignore
README.md
config.dev.php
php.Dockerfile

There's no issue for this but I have the following changes to config files.
Updated the backups location for rehydrating a database in the markdown readme.
Added the requirements for docker to allow image uploads
Changed the cache directory and added a git ignore for the files

Config file changes for docker and backup location

---

system/lib/ork3/class.Player.php

245 Add order to player attendance

---

orkui/model/model.Award.php

243 Sort Awards in Player Admin Page

---

system/lib/ork3/class.Report.php

248 Limit reports to active players only

---

orkui/controller/controller.Admin.php
orkui/model/model.Kingdom.php
orkui/template/default/Admin_editparks.tpl
system/lib/ork3/class.Park.php

Add ability to update park names at the kingdom level or higher. Force Abbreviations to uppercase.

Add ability to update park names at the kingdom level or higher

---

orkui/template/default/Admin_createplayer.tpl

Fixes #257 by removing the waiver div when adding new players

Remove add waiver option on create new player

---

db-migrations/2021-04-12-add-park-member-since-col
orkui/controller/controller.Admin.php
orkui/template/default/Admin_player.tpl
orkui/template/default/Player_index.tpl
system/lib/ork3/class.Player.php

This PR requires a db-migration for the production DB. It is already in place on the DEV DB

Issue237 resident date field

---

orkui/model/model.Award.php
orkui/template/default/Admin_player.tpl
orkui/template/default/Atlas_index.tpl
orkui/template/default/Atlas_map.tpl
orkui/template/default/Kingdom_map.tpl
orkui/template/default/Player_index.tpl
system/lib/ork3/class.Kingdom.php

Updated SQL and moved OfficerRole check to return array logic so that kingdom custom awards could be fetched. Fixed Award/Title bug stacking in Player award view

Issue253 dropdown missing custom awards

---

orkui/template/default/Admin_player.tpl
orkui/template/default/Atlas_index.tpl
orkui/template/default/Atlas_map.tpl
orkui/template/default/Kingdom_map.tpl
orkui/template/default/Player_index.tpl
system/lib/ork3/class.Player.php

Added a browser cache bust string that uses the record modified date for the player.

Issue233 player image browser cache bust

---

db-migrations/2021-04-13-add-player-corpora-columns
orkui/controller/controller.Admin.php
orkui/controller/controller.Reports.php
orkui/model/model.Reports.php
orkui/template/default/Admin_player.tpl
orkui/template/default/Kingdom_index.tpl
orkui/template/default/Park_index.tpl
orkui/template/default/Player_index.tpl
orkui/template/default/Reports_corpora.tpl
orkui/template/default/Reports_reeve.tpl
system/lib/ork3/class.Player.php
system/lib/ork3/class.Report.php

This PR requires a DB migration. Already done for testing on DEV DB

Issue115 reeve corpora fields and reports

---

orkui/controller/controller.Admin.php
orkui/controller/controller.Kingdom.php
orkui/controller/controller.Park.php
orkui/template/default/Admin_player.tpl
orkui/template/default/Kingdom_index.tpl
orkui/template/default/Park_index.tpl

This file size takes into account the added 1.333 bytes per byte that the base64 encode that is used on the backend adds

Added file size info to admin image box, added file size errors

---

orkui/template/default/Admin_player.tpl

Confirmation dialog testing required

Added confirmations to Player remove award, unit, title, strip all awards

---

orkui/template/default/Admin_unit.tpl

I wasn't able to test whether URL changes worked or not, but the field is there now, and it does populate itself with existing URL entry if there is one.

URL field added to edit unit page

---

orkui/template/default/Admin_player.tpl
orkui/template/default/Admin_unit.tpl
orkui/template/default/Player_index.tpl
system/lib/ork3/class.Report.php

Changelog
(Fix) Updated player dues display to hide expiration of Dues For Life records (Tzulah)
(Fix) Unit website URL now editable on the Unit Admin page (Tzulah)
(Fix) Updated sorting of Dues Paid list (Himanshu)
(Fix) Updated old reports to use the new dues table (Fog)
(Enhancement) Added confirmation dialogs to Player Admin (remove award, remove title, strip awards, remove unit, remove historic note) (Fog)
(Fix) Issue with GivenBy not working on Player Admin

2021 apr 26 release

---

system/lib/ork3/class.Kingdom.php
system/lib/ork3/class.Park.php

Release fixes URL link bug for champion on kd/park index

2021 aug 09 release

---

system/lib/ork3/class.Kingdom.php

Fixes #299 
Can see the extra Abbreviation in the call results

299 add abbreviation to getkingdoms

---

orkui/controller/controller.Player.php
orkui/model/model.Player.php
orkui/template/default/Player_index.tpl
orkui/template/default/Reports_playerawardrecommendations.tpl
system/lib/ork3/class.Player.php
system/lib/ork3/class.Report.php

giver or receiver of an award recommendation can delete it (soft delete)

add delete action for award recs

---

orkui/template/default/Admin_player.tpl

Fix for issue 324 custom pronouns

---

system/lib/ork3/common.php

The SQL code to fix up the database needs to be run first and then deploy master with this fix

Fix for #343 No GMR for new parks

---

system/lib/ork3/class.Player.php

Fix for reconcile credits not working #351

---

system/lib/ork3/class.Kingdom.php

Remove inactive principalities from list

---

orkui/controller/controller.Admin.php
orkui/template/default/Admin_editkingdom.tpl

Fix for #358 
Somehow the comparison for "New" changed, maybe in new PHP ?

Fix for 358 cannot add awards
